export const youtuberList = [
  {
    num: '0',
    name: '침착맨',
    channelId: 'UCUj6rrhMTR9pipbAWBAMvUQ',
    profilepic: '/imgsrc/chimchackman.jpeg',
  },
  {
    num: '1',
    name: '슈카',
    channelId: 'UCsJ6RuBiTVWRX156FVbeaGg',
    profilepic: '/imgsrc/shuka.jpeg',
  },
  {
    num: '2',
    name: '걍밍경',
    channelId: 'UCfqVrM2cvwxG3-EvxbsN0KQ',
    profilepic: '/imgsrc/kangminkyong.jpeg',
  },
  {
    num: '3',
    name: '콬TV',
    channelId: 'UCybPxZoFDPR1qbN04daAc2g',
    profilepic: '/imgsrc/koktv.jpeg',
  },
  {
    num: '4',
    name: 'GYM JONG KOOK',
    channelId: 'UCoe-0EVDJnjlSoPK8ygcGwQ',
    profilepic: '/imgsrc/gymjongkook.jpeg',
  },
  {
    num: '5',
    name: '애니멀봐',
    channelId: 'UC22go5LdQEw-iDuxFb4C0hw',
    profilepic: '/imgsrc/animalsee.jpeg',
  },
  {
    num: '6',
    name: '김해준',
    channelId: 'UCPwGQuQiIqvUTfa_OKZL7qQ',
    profilepic: '/imgsrc/kimhaejun.jpeg',
  },
  {
    num: '7',
    name: '짧은대본',
    channelId: 'UChgOgRNxrtCcVARDQT_c-Zg',
    profilepic: '/imgsrc/shortsenario.jpeg',
  },
  {
    num: '8',
    name: '[햄지]Hamzy',
    channelId: 'UC1EiHIhV6UDRWOY6BaEavdw',
    profilepic: '/imgsrc/hanzy.jpeg',
  },
  {
    num: '9',
    name: '생활코딩',
    channelId: 'UCvc8kv-i5fvFTJBFAk6n1SA',
    profilepic: '/imgsrc/senghwalcoding.jpeg',
  },
  {
    num: '10',
    name: 'freeCodeCamp',
    channelId: 'UC1emV4A8liRs9p80CY8ElUQ',
    profilepic: '/imgsrc/freecodecamp.jpeg',
  },
  {
    num: '11',
    name: 'WebDevSimplified',
    channelId: 'UCFbNIlppjAuEX4znoulh0Cw',
    profilepic: '/imgsrc/webdevsimplified.jpeg',
  },
  {
    num: '12',
    name: 'SonnySangha',
    channelId: 'UCqeTj_QAnNlmt7FwzNwHZnA',
    profilepic: '/imgsrc/sonnysangha.jpeg',
  },
  {
    num: '13',
    name: '코딩앙마',
    channelId: 'UCxft4RZ8lrK_BdPNz8NOP7Q',
    profilepic: '/imgsrc/codingangma.jpeg',
  },
  {
    num: '14',
    name: 'LamaDev',
    channelId: 'UCOxWrX5MIdXIeRNaXC3sqIg',
    profilepic: '/imgsrc/lamadev.jpeg',
  },
  {
    num: '15',
    name: 'TraversyMedia',
    channelId: 'UC29ju8bIPH5as8OGnQzwJyA',
    profilepic: '/imgsrc/traversymedia.jpeg',
  },
];
